//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutionCloudWeb.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quester_ShareAnArchivedTest
    {
        public long ShareAnArchivedTestId { get; set; }
        public Nullable<long> WordId { get; set; }
        public Nullable<long> ExamId { get; set; }
        public Nullable<System.Guid> Guid { get; set; }
        public Nullable<long> UserId { get; set; }
        public string Password { get; set; }
        public string TestID { get; set; }
        public string LastName { get; set; }
        public string SentUserID { get; set; }
        public string Word { get; set; }
        public string Pronounciation { get; set; }
        public string Phrase { get; set; }
        public string Hint { get; set; }
        public string Definition { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> ShareOnline { get; set; }
        public string CreatedDate { get; set; }
        public string UpdatedDate { get; set; }
        public string CreatedOn { get; set; }
    }
}
