//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutionCloudWeb.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quester_ExamWord
    {
        public long Id { get; set; }
        public long ExamId { get; set; }
        public long WordId { get; set; }
    
        public virtual Quester_Exam Quester_Exam { get; set; }
        public virtual Quester_Word Quester_Word { get; set; }
    }
}
