//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutionCloudWeb.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quester_ForgotPassword
    {
        public int id { get; set; }
        public long userid { get; set; }
        public System.Guid passwordguid { get; set; }
        public System.DateTime timestamp { get; set; }
        public bool status { get; set; }
    }
}
