//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutionCloudWeb.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quester_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Quester_User()
        {
            this.Quester_Category = new HashSet<Quester_Category>();
            this.Quester_TreeView = new HashSet<Quester_TreeView>();
        }
    
        public long UserId { get; set; }
        public System.Guid UserGuid { get; set; }
        public string Forename { get; set; }
        public string Surname { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Webname { get; set; }
        public System.DateTime AccountCreatedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsSuspended { get; set; }
        public bool PushStatus { get; set; }
        public System.DateTime ProfileLastEditedDate { get; set; }
        public string ProfileImage { get; set; }
        public string email { get; set; }
        public Nullable<bool> Islogged { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quester_Category> Quester_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quester_TreeView> Quester_TreeView { get; set; }
    }
}
