//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutionCloudWeb.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShareExamResult
    {
        public long Id { get; set; }
        public Nullable<System.Guid> Guid { get; set; }
        public string UserID { get; set; }
        public Nullable<long> ExamId { get; set; }
        public Nullable<long> WordId { get; set; }
        public Nullable<bool> IsCorrect { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    }
}
