//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutionCloudWeb.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCrosswordWord
    {
        public long Id { get; set; }
        public long WordId { get; set; }
        public long CrosswordId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual tCrossword tCrossword { get; set; }
        public virtual tWord tWord { get; set; }
    }
}
