//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutionCloudWeb.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCrossword
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tCrossword()
        {
            this.tCrosswordWords = new HashSet<tCrosswordWord>();
        }
    
        public long CrosswordId { get; set; }
        public long UserId { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public bool IsDeleted { get; set; }
        public string CrosswordSaveString { get; set; }
        public bool IsCompleted { get; set; }
    
        public virtual tUser tUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCrosswordWord> tCrosswordWords { get; set; }
    }
}
