//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutionCloudWeb.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestShared
    {
        public decimal TestSharedID { get; set; }
        public string SentUserID { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
        public string WordId { get; set; }
        public string Password { get; set; }
        public string TestID { get; set; }
        public string LastName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedOn { get; set; }
        public string Pronounciation { get; set; }
        public string Phrase { get; set; }
        public string Hint { get; set; }
        public string Definition { get; set; }
        public Nullable<bool> ShareOnline { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.Guid> Guid { get; set; }
        public string Word { get; set; }
        public Nullable<bool> Retrieve { get; set; }
        public string Title { get; set; }
        public string TestTime { get; set; }
        public string TimePerWord { get; set; }
    }
}
