//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutionCloudWeb.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tExamResult
    {
        public long Id { get; set; }
        public System.Guid Guid { get; set; }
        public long ExamId { get; set; }
        public long WordId { get; set; }
        public bool IsCorrect { get; set; }
        public System.DateTime Timestamp { get; set; }
    
        public virtual tExam tExam { get; set; }
        public virtual tWord tWord { get; set; }
    }
}
