//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutionCloudWeb.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tWord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tWord()
        {
            this.tCrosswordWords = new HashSet<tCrosswordWord>();
            this.tExamResults = new HashSet<tExamResult>();
            this.tExamWords = new HashSet<tExamWord>();
            this.tUserFavouriteWords = new HashSet<tUserFavouriteWord>();
            this.tUserSkippedWords = new HashSet<tUserSkippedWord>();
        }
    
        public long WordId { get; set; }
        public System.Guid Guid { get; set; }
        public long UserId { get; set; }
        public string Word { get; set; }
        public string Pronounciation { get; set; }
        public string Phrase { get; set; }
        public string Hint { get; set; }
        public string Definition { get; set; }
        public bool IsActive { get; set; }
        public bool ShareOnline { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCrosswordWord> tCrosswordWords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tExamResult> tExamResults { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tExamWord> tExamWords { get; set; }
        public virtual tUser tUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tUserFavouriteWord> tUserFavouriteWords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tUserSkippedWord> tUserSkippedWords { get; set; }
    }
}
