//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutionCloudWeb.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class VerifyEmail
    {
        public decimal ID { get; set; }
        public string Email { get; set; }
        public Nullable<int> Code { get; set; }
        public Nullable<byte> Active { get; set; }
    }
}
